---
- name: Check if WP-CLI is installed
  ansible.builtin.command: |
    sudo -u apache /usr/local/bin/wp --version --allow-root
  register: wpcli_installed
  changed_when: false
  ignore_errors: true

- name: Delete working directory
  ansible.builtin.file:
    path: '{{ wp_cli_working_dir }}'
    state: absent
  when: wpcli_installed is failed

- name: Create working directory
  ansible.builtin.file:
    path: '{{ wp_cli_working_dir }}'
    state: directory
    mode: 0755
  when: wpcli_installed is failed

- name: Retrieve WP-CLI execute file
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: '{{ wp_cli_working_dir }}'
    owner: root
    group: root
    mode: 0755
  when: wpcli_installed is failed

- name: Register WP-CLI command
  become: yes
  ansible.builtin.command: |
    mv wp-cli.phar /usr/local/bin/wp
  args:
    chdir: '{{ wp_cli_working_dir }}'
  register: wpcli_registered
  changed_when: wpcli_registered.rc == 0
  when: wpcli_installed is failed
