---
- name: Verify
  hosts: all

  tasks:
    - name: Check whether WP-CLI installed
      ansible.builtin.command: |
        sudo -u apache /usr/local/bin/wp cli version
      register: wpcli_installed
      changed_when: false

    - name: Check OS version
      ansible.builtin.command: cat /etc/redhat-release
      register: os_version
      changed_when: false

    - name: Make sure WP-CLI is installed
      ansible.builtin.debug:
        var: wpcli_installed

    - name: Show OS version
      ansible.builtin.debug:
        var: os_version
